# -*- coding: utf-8 -*-
"""Analise_Exploratória.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IRDGKXzQhik4sBcGAAy2AYMGQ70RWA7p
"""

#Importando as bibliotecas
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use("seaborn")

#Upload do arquivo
from google.colab import files 
arq = files.upload()

#criando nosso DataFrame
df = pd.read_excel("AdventureWorks.xlsx")

#Visualizando as 5 primeiras linhas
df.head()

#Quantidade de linhas e colunas
df.shape

#Verificando os tipos de dados
df.dtypes

#Qual a receita total?
df["Valor Venda"].sum()

#Qual o custo total?
df["custo"] = df["Custo Unitário"].mul(df["Quantidade"]) #Criando a coluna de custo

df.head(1)

#Qual o custo total?
round(df["custo"].sum(), 2)

#Agora que temos a receita e custo e o total, podemosahar o lucro total
#Vamos criar uma coluna de lucroque será receita - custo
df["lucro"] = df["Valor Venda"] - df["custo"]

df.head(1)

#Total lucro
round(df["lucro"].sum(), 2)

#Criando uma coluna com total de dias para enviar o produto
df["Tempo_envio"] = df["Data Envio"] - df["Data Venda"]

df.head(1)

#Extraindo apenas os dias
df["Tempo_envio"] = (df["Data Envio"] - ["Data Vendas"]).dt.days

